# Source: jxboot-helmfile-resources/templates/jx-gcjobs-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gcjobs
  namespace: "jx"
  annotations:
    meta.helm.sh/release-name: 'jxboot-helmfile-resources'
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
rules:
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - delete
      - list
