# Source: jxboot-helmfile-resources/templates/jx-gcjobs-sa.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jx-gcjobs
  namespace: "jx"
  annotations:
    meta.helm.sh/release-name: 'jxboot-helmfile-resources'
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
